env:
  browser: true
  es2021: true
extends: eslint:recommended
parserOptions:
  ecmaVersion: latest
  sourceType: module
globals:
  ethers: true
  describe: true
  it: true
rules: {}
ignorePatterns:
  - hardhat.config.cjs
  - coverage/**
  - cache/**
  - artifacts/**
