on: ["push", "pull_request"]

name: Test Coveralls

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v1

    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x

    - name: Install
      run: npm install
        
    - name: Lint
      run: npm run lint

    - name: Model Check
      run: npm run check
      timeout-minutes: 2

    - name: Gas Report
      env:
        CMC: ${{ secrets.CMC }}
      run: npm run gas

    - name: Test Coverage
      run: npm run coverage

    - name: Upload to Coveralls
      uses: coverallsapp/github-action@v2

    - name: Full Model Test
      run: npm test
      env:
        FULL_TEST: true